set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g status-position top
set -g status-justify absolute-centre
set -g mode-keys vi
set -g window-status-current-style "fg=blue bg=default bold"
set -g status-style "bg=default"
set -g history-limit 1000000
set -g escape-time 0             # zero-out escape time delay
set -g focus-events on           # report when a paine/terminal gains or loses focus (good for nvim)

#Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-right ""
set -g status-left-length 100
set -g status-style "fg=${gray_light}, bg=default"
set -g status-left "#[fg=${green_soft}, bold] #S #[fg=${gray_light}, nobold]"
set -g window-status-current-format "#[fg${cyan_soft}, bold]  #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light}, bg=default"
set -g mode-style "fg=${gray_dark}, bg=${blue_muted}"
set -g pane-active-border-style "fg=${gray_medium}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

set -g @resurrect-strategy-nvim 'session'

bind r source-file "~/.config/tmux/tmux.conf"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes (repeatable)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Remove the confirmation before deleting a window
unbind &
bind & kill-window

# Remove the confirmation before deleting a window
unbind x
bind x kill-pane

run '~/.config/tmux/plugins/tpm/tpm'
