require('plugin_configs.comment')
require('plugin_configs.autoClose')
require('plugin_configs.cmp')
require('plugin_configs.gitSigns')
require('plugin_configs.harpoon')
require('plugin_configs.indentBlankLine')
require('plugin_configs.lazygit')
require('plugin_configs.lsp')
require('plugin_configs.notify')
-- require('plugin_configs.obsidian')
require('plugin_configs.telescope')
require('plugin_configs.treesitter')
